/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.59
 * Generated at: 2020-11-07 13:11:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import entityClass.User;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/theme/meta.jsp", Long.valueOf(1604753442003L));
    _jspx_dependants.put("/theme/footer.jsp", Long.valueOf(1604752446826L));
    _jspx_dependants.put("/theme/header.jsp", Long.valueOf(1604754689831L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("entityClass.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no, minimal-ui\">\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>");
      out.print( "Rent Car" + (request.getParameter("title") == null?"":request.getParameter("title")));
      out.write("</title>\n");
      out.write("\n");
      out.write("\n");
      out.write("<link href=\"");
      out.print( getServletContext().getInitParameter("DomainName"));
      out.write("/theme/lib/Master.css\" rel=\"stylesheet\" />\n");
      out.write("\n");
      out.write("\n");
      out.write("<link href=\"");
      out.print( getServletContext().getInitParameter("DomainName"));
      out.write("/theme/lib/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\" />\n");
      out.write("<link href=\"");
      out.print( getServletContext().getInitParameter("DomainName"));
      out.write("/theme/lib/datatable/datatables.min.css\" rel=\"stylesheet\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\n");
      out.write("\n");
      out.write("\n");
      out.write("<script src=\"");
      out.print( getServletContext().getInitParameter("DomainName"));
      out.write("/theme/lib/jquery/jquery-3.5.1.min.js\"></script>\n");
      out.write("<script src=\"");
      out.print( getServletContext().getInitParameter("DomainName"));
      out.write("/theme/lib/bootstrap/js/bootstrap.min.js\"></script>\n");
      out.write("<script src=\"");
      out.print( getServletContext().getInitParameter("DomainName"));
      out.write("/theme/lib/datatable/datatables.min.js\"></script>\n");
      out.write("\n");
      out.write("  \n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("\n");
      out.write("<nav class=\"navbar navbar-default\" style=\"padding-top: 10px; padding-bottom: 10px;\">\n");
      out.write("    <div class=\"container-fluid\">\n");
      out.write("        <div class=\"navbar-header\">\n");
      out.write("            <a class=\"\" href=\"");
      out.print( getServletContext().getInitParameter("DomainName"));
      out.write("\">\n");
      out.write("                <img class=\"pull-left\" src=\"../media/logo.png\" alt=\"Flowers in Chania\" width=\"64\" height=\"50\">\n");
      out.write("            </a>\n");
      out.write("            <a class=\"navbar-brand\" href=\"");
      out.print( getServletContext().getInitParameter("DomainName"));
      out.write("\" style=\"padding-left: 30px\">Artwork Sales.com\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("        <ul class=\"nav navbar-nav\">\n");
      out.write("            ");

                User user = null;
            
      out.write("\n");
      out.write("\n");
      out.write("            ");
      out.write("\n");
      out.write("            <li class=\"art-list\"><a href=\"");
      out.print( getServletContext().getInitParameter("DomainName"));
      out.write("/pages/Home.aspx\">Home</a></li>\n");
      out.write("\n");
      out.write("            ");

                if (user != null) {
                    String role = user.getRole();
                    if (!role.equals("A")) {
            
      out.write("\n");
      out.write("\n");
      out.write("            <li class=\"art-list\"><a href=\"");
      out.print( getServletContext().getInitParameter("DomainName"));
      out.write("/pages/Shop.aspx\">Shop</a></li>\n");
      out.write("\n");
      out.write("            ");

                }
            
      out.write("\n");
      out.write("            ");
      out.write("\n");
      out.write("            <li class=\"dropdown\">\n");
      out.write("                <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">My Account<span class=\"caret\"></span></a>\n");
      out.write("                <ul class=\"dropdown-menu\">\n");
      out.write("                    <li class=\"\"><a href=\"");
      out.print( getServletContext().getInitParameter("DomainName"));
      out.write("/pages/MyAccount.aspx\">My Account details</a></li>\n");
      out.write("                    <li class=\"\"><a href=\"");
      out.print( getServletContext().getInitParameter("DomainName"));
      out.write("/pages/ChangePassword.aspx?post=0\">Change Password</a></li>\n");
      out.write("                    <li class=\"\"><a href=\"#\" runat=\"server\" onserverclick=\"logout\">Logout</a></li>\n");
      out.write("                </ul>\n");
      out.write("            </li>\n");
      out.write("            ");

                if (role.equals("C") || role.equals("B")) {
            
      out.write("\n");
      out.write("            ");
      out.write("\n");
      out.write("            <li class=\"art-list\"><a href=\"");
      out.print( getServletContext().getInitParameter("DomainName"));
      out.write("/pages/MyGallery.aspx\">My Gallery</a></li>\n");
      out.write("            <li class=\"art-list\"><a href=\"");
      out.print( getServletContext().getInitParameter("DomainName"));
      out.write("/pages/MyCart.aspx\">My Cart</a></li>\n");
      out.write("            <li class=\"art-list\"><a href=\"");
      out.print( getServletContext().getInitParameter("DomainName"));
      out.write("/pages/MyOrder.aspx\">My Order</a></li>\n");
      out.write("            <li class=\"art-list\"><a href=\"");
      out.print( getServletContext().getInitParameter("DomainName"));
      out.write("/pages/MyWishList.aspx\">My Wish List</a></li>\n");
      out.write("                ");

                } else if (role.equals("A") || role.equals("B")) {
                
      out.write("\n");
      out.write("                ");
      out.write("\n");
      out.write("            <li class=\"art-list\"><a href=\"");
      out.print( getServletContext().getInitParameter("DomainName"));
      out.write("/pages/AddArt.aspx\">Add New Art</a></li>\n");
      out.write("            <li class=\"art-list\"><a href=\"");
      out.print( getServletContext().getInitParameter("DomainName"));
      out.write("/pages/ArtWorkSales.aspx\">My Artwork</a></li>\n");
      out.write("            <li class=\"art-list\"><a href=\"");
      out.print( getServletContext().getInitParameter("DomainName"));
      out.write("/pages/MyGallery.aspx\">My Gallery</a></li>\n");
      out.write("                ");

                    }
                } else {
                
      out.write("\n");
      out.write("                ");
      out.write("\n");
      out.write("            <li class=\"art-list\"><a href=\"");
      out.print( getServletContext().getInitParameter("DomainName"));
      out.write("/pages/Shop.aspx\">Shop</a></li>\n");
      out.write("            <li class=\"art-list\"><a href=\"");
      out.print( getServletContext().getInitParameter("DomainName"));
      out.write("%>/pages/Register.aspx\">Register</a></li>\n");
      out.write("            <li class=\"art-list\"><a href=\"");
      out.print( getServletContext().getInitParameter("DomainName"));
      out.write("/pages/Login.aspx\">Login</a></li>\n");
      out.write("                ");

                    }
                
      out.write("\n");
      out.write("        </ul>\n");
      out.write("\n");
      out.write("        <div class=\"navbar-header pull-right\">\n");
      out.write("            <a class=\"\" href=\"\">\n");
      out.write("                <img src=\"\" alt=\"\"\n");
      out.write("                     width=\"50\"\n");
      out.write("                     height=\"50\"\n");
      out.write("                     class=\"img-circle\">\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</nav>");
      out.write("  \n");
      out.write("        <h1>Hello World!</h1>\n");
      out.write("        ");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("Test Footer");
      out.write("  \n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
